### ISSUE TITLE
Polyfill PHP 7.3+ getallheaders()

### ISSUE THREAD

**Issue by Krinkle** [symfony/polyfill#245]
See also:
* <https://www.php.net/getallheaders> (PHP 7.3)
* <https://www.php.net/apache-request-headers> (PHP 7.3)
* <https://bugs.php.net/bug.php?id=62596>

There is prior art at <https://github.com/ralouphie/getallheaders>, which was adopted by the popular guzzle/psr7 package ([pull request](https://github.com/guzzle/psr7/pull/162/commits/ec88056249722acc235c4e8d0bfec7efcb3b6b3b)).

**Comment by Krinkle** [comment]
If there is agreement to accept a polyfill for this, I'd be interested to help and write the patch for it. My first question would be to know whether it's preferred to re-use ralouphie/getallheaders by dependency, or whether to embed it (effectively a fork).

**Comment by nicolas-grekas** [comment]
The issue is that it's not possible to polyfill correctly this function. The linked package works in some specific situations, but it's impossible to have a polyfill that works in every situations. That's why we didn't add this function here. Use ralouphie/getallheaders if it's ok for you.

**Comment by Krinkle** [comment]
@nicolas-grekas What aspect of `getallheaders` is impossible to polyfill?

**Comment by Krinkle** [comment]
@nicolas-grekas What aspect of `getallheaders()` is impossible to polyfill?

**Comment by nicolas-grekas** [comment]
I'm going to close here because `ralouphie/getallheaders` is fine for ppl that want this, and also because using this function should be discouraged. It uses global state and the fact that it's not available on all SAPIs is because *it doesn't make sense* on the unsupported SAPIs. Adding a polyfill for something that doesn't make sense... doesn't make sense here :)
