### ISSUE TITLE
normalizer_is_normalized has nullable string parameter

### ISSUE THREAD

**Issue by othercorey** [symfony/polyfill#423]
The normalizer_is_normalized pollyfill `string` parameter is nullable while php implementation is not.

https://github.com/symfony/polyfill-intl-normalizer/blob/main/bootstrap80.php#L14-L16

https://www.php.net/manual/en/normalizer.isnormalized.php

**Comment by stof** [comment]
This is done because in non-strict mode, PHP accepts strings in core functions using a `string` typehint (triggering a deprecation in PHP 8.1+), which we cannot fully emulate in userland (that's part of the reasons why this behavior is deprecated in PHP 8.1 btw). See https://github.com/symfony/polyfill/pull/330

**Comment by othercorey** [comment]
Thanks for explaining! This definitely sounds correct for pollyfill and the issue I ran into updating psalm is not important.
