### ISSUE TITLE
polyfill-mbstring should require polyfill-iconv or ext-iconv

### ISSUE THREAD

**Issue by moderndeveloperllc** [symfony/polyfill#66]
The `polyfill-mbstring` library depends on `iconv`, but does not require the `polyfill-iconv` library or `ext-iconv`. This can be an issue for things such as minimal PHP docker installs that include `--configure = --disable-all` before listing specific extensions to build.

**Comment by nicolas-grekas** [comment]
This is on purpose: iconv is a heavy lib, if you need it, you should `composer require`.
Btw, minimal docker setups really should embed the native iconv+mbstring. They are much faster than the PHP versions.

**Comment by stof** [comment]
@moderndeveloperllc we don't have the require rule for ext-iconv because we don't have the provide rule in the polyfill either to allow to use the iconv polyfill, and we don't want to force downloading the iconv polyfill.
See https://github.com/symfony/polyfill/pull/54/files which works on fixing this (and would actually allow packages to dependd on ext-mbstring and letting projects decide whether they want to include the polyfill to fulfill it), but it suffers from a Composer/Packagist bug related to packages polyfilling extensions
